### ISSUE TITLE
Missing timber metadata in log file

### ISSUE THREAD

**Issue by thomas-neitmann** [atorus-research/timber#4] opened 2021-11-23 10:11 UTC
I just installed the latest version of {timber} from the `main` branch using `renv::install("atorus-research/timber")`. The log file that got created during my initial testing is missing the timber metadata. In addition the formatting of the `Warnings` and `errors` (shouldn't it be `Errors`?) looks off...

```
--------------------------------------------------------------------------------
-                               timber Metadata                                -
--------------------------------------------------------------------------------
This log was generated using timber 
timber package version: 
timber license: 
timber build: 
timber link to repository: https://github.com/atorus-research/timber
--------------------------------------------------------------------------------
-                               User Information                               -
--------------------------------------------------------------------------------
User: neitmant
--------------------------------------------------------------------------------
-                             Session Information                              -
--------------------------------------------------------------------------------
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils    
[6] methods   base     

other attached packages:
[1] patchwork_1.1.1 ggplot2_3.3.2   stringr_1.4.0  
[4] dplyr_1.0.2     rice_2.0       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        pillar_1.4.6      compiler_4.0.3   
 [4] forcats_0.5.0     tools_4.0.3       getPass_0.2-2    
 [7] digest_0.6.27     jsonlite_1.7.1    memoise_1.1.0    
[10] lifecycle_0.2.0   tibble_3.0.4      gtable_0.3.0     
[13] pkgconfig_2.0.3   rlang_0.4.8       cli_2.1.0        
[16] rstudioapi_0.11   curl_4.3          haven_2.3.1      
[19] withr_2.3.0       httr_1.4.2        generics_0.1.0   
[22] vctrs_0.3.4       hms_0.5.3         grid_4.0.3       
[25] tidyselect_1.1.0  glue_1.4.2        R6_2.5.0         
[28] fansi_0.4.1       timber_0.0.0.9001 farver_2.0.3     
[31] purrr_0.3.4       readr_1.4.0       magrittr_1.5     
[34] scales_1.1.1      ellipsis_0.3.1    assertthat_0.2.1 
[37] colorspace_1.4-1  renv_0.13.2       labeling_0.4.2   
[40] stringi_1.5.3     munsell_0.5.0     crayon_1.3.4     
--------------------------------------------------------------------------------
-                               Masked Functions                               -
--------------------------------------------------------------------------------
function `title` from {package:graphics} by .GlobalEnv
function `table` from {package:base} by .GlobalEnv
function `enexpr` from {package:dplyr} by package:ggplot2
function `enexprs` from {package:dplyr} by package:ggplot2
function `enquo` from {package:dplyr} by package:ggplot2
function `enquos` from {package:dplyr} by package:ggplot2
function `ensym` from {package:dplyr} by package:ggplot2
function `ensyms` from {package:dplyr} by package:ggplot2
function `expr` from {package:dplyr} by package:ggplot2
function `quo` from {package:dplyr} by package:ggplot2
function `quo_name` from {package:dplyr} by package:ggplot2
function `quos` from {package:dplyr} by package:ggplot2
function `sym` from {package:dplyr} by package:ggplot2
function `syms` from {package:dplyr} by package:ggplot2
function `vars` from {package:dplyr} by package:ggplot2
function `Position` from {package:base} by package:ggplot2
function `%>%` from {package:dplyr} by package:stringr
function `filter` from {package:stats} by package:dplyr
function `lag` from {package:stats} by package:dplyr
function `intersect` from {package:base} by package:dplyr
function `setdiff` from {package:base} by package:dplyr
function `setequal` from {package:base} by package:dplyr
function `union` from {package:base} by package:dplyr
function `plot` from {package:base} by package:graphics
function `install.packages` from {package:utils} by renv:shims
function `remove.packages` from {package:utils} by renv:shims
function `update.packages` from {package:utils} by renv:shims
function `body<-` from {package:base} by package:methods
function `kronecker` from {package:base} by package:methods
--------------------------------------------------------------------------------
-                         Program Run Time Information                         -
--------------------------------------------------------------------------------
Start time: 2021-11-23 11:06:58 CET
End time: 2021-11-23 11:07:00 CET
Run time: 2 seconds
--------------------------------------------------------------------------------
-                             Errors and Warnings                              -
--------------------------------------------------------------------------------
errors:
	NULL
Warnings:
	
--------------------------------------------------------------------------------
-                               Log Output File                                -
--------------------------------------------------------------------------------
Log name: g_eortc_ql.log
Log path: /home/bceuser/neitmant/arrow
```

**Comment by kodesiba** [comment] 2021-11-23 20:26
errors/Errors issue is simple and I'll fix soon, for the other part I can look at how we get these elements as the only reason the metadata section would be empty would be that the way we get that information is flawed.  I can definitely take a look at these things in the next couple weeks.

**Comment by thomasp-b** [comment] 2022-03-03 11:18
@thomas-neitmann, thank you for your comments and suggestions. I'm in the process of investigating the issue you reported with blank session info. I cannot reproduce the issue. Could you please let me know if you can reproduce it, and how? Thank you.

Also I've pushed a fix for capitalising "errors" and displaying a meaningful message when there are no errors or warnings.

**Closed** 2022-03-25 18:28 UTC
Labels: bug
